### ISSUE TITLE
No Database found !

### ISSUE THREAD

**Issue by elarib** [myselfjivan/BloodDonation#1]
Hi, 
 i wish you're going well... You know i cloned your project, but it seems you didn't upload the database .Can you upload it ASAP :)
Thank you :+1:

**Comment by myselfjivan** [comment]
Thanks for reporting the issue,
I have dumped primary database file you can import it and make connections accordingly. 

https://github.com/myselfjivan/BloodDonation/blob/master/database_export.sql

if your done with the issue then close it...
